import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import dynamic from 'next/dynamic'
import { Footer } from '@/components/footer'
const DynamicNavbar = dynamic(() => import('@/components/navbar'), { ssr: false })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}
export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <DynamicNavbar />
            <main className="mt-20" id="main">
               {children}
            </main>
            <Footer />
         </body>
      </html>
   )
}
